
MODULE_NAME = '[class="DashboardHeaderTitle-title"]'
BUTTON_ACCEPT_COOKIE = '#onetrust-accept-btn-handler'
BUTTON_LOGIN_1 = '.SiteNavLoginSection-loginButton button'
BUTTON_LOGIN_2 = '.UILoadingButton'
LOCATOR_AFTER_AUTORIZATION = '[class="UIDiv RecentFeed"]'
PRESS_PLUS = '[class="DashboardHeaderActions"] [class*="MenuIconWithTool"]:first-child'
CREATE_NEW_MODULE = '.DashboardAddSetsModal-createButton a'
CLOSE_AD = '.ckk0ebs'
PRESS_IMPORT_WORLD = '.UILink'
PRESS_IMPORT_BUTTOM = '[class="ImportTerms-importButtonWrap"] [class="UIButton UIButton--hero"]'
BLOKS_WORD = '//div[@class="TermRows-termRowWrap"][position()<last()]'
CLICK_ON_TEXT = '//div[@class="TermContent-side TermContent-side--definition"]//div[@data-testid="PMEditor"]'
CLICK_ON_WORD = './/div[@class="TermContent-side TermContent-side--word"]//div[@data-testid="PMEditor"]'
CLICK_ON_TEXT_ENG = './/div[@class="TermContent-side TermContent-side--definition"]//div[@class="PMEditor pc1cm7j lang-en notranslate"]'
CLICK_ON_TEXT_ENG_DOM = '.TermContent-side.TermContent-side--definition .PMEditor.lang-en.notranslate'
CLICK_ON_TEXT_NEXT = './/div[@class="TermContent-side TermContent-side--definition"]//div[@data-testid="PMEditor"]'
PRESS_LANGUAGE_SHOISE2 = '//div[@class="DefinitionSide"]//div[@class="LanguageBarSide"]//button[@class="UILink is-Popover is-Tooltip UIOverlayTrigger-target"]'
SHOISE_LANGUAGE_RUS = './/div[@id="react-select-3--option-3"]'
SHOISE_LANGUAGE_UKR = './/div[@id="react-select-3--option-4"]'
PRESS_LANGUAGE_SHOISE1 = '//div[@class="WordSide is-active"]//div[@class="LanguageBarSide"]//button[@class="UILink is-Popover is-Tooltip UIOverlayTrigger-target"]'
SHOISE_LANGUAGE_ENG = '//div[@id="react-select-2--option-1"]'
SHOISE_WORD = 'div[class*="AutosuggestContext"] div  div[class*="AutosuggestContextItem"]:first-child'
IMJ_BUTTON = './/div[@class="DefinitionSide"]//div[@class="ImageUploadComponent"]'
HEADER = '[class="sets new create-set has-no-footer has-sticky-header qad-is-showing theme-night"]'
MODULE_NAME_TYPE = '[class="CreateSetHeader-textarea CreateSetHeader-title"] .AutoExpandTextarea-textarea'